Kuwait Theme: Progress Wheel Component
IDEMSInternational/open-app-builder pull request #2558
Opened 2024-11-26 07:35 UTC by FaithDaka

PR Checklist

- [x] PR title descriptive (can be used in release notes)

## Description

`plh_progress_wheel` created and styled. Corresponding debug sheet: [Link](https://docs.google.com/spreadsheets/d/1aXtJi0oCxsHISq6m-xwJi_R_BSpUj4wHQlO_g4LUjSY/edit?usp=sharing)

## Author Notes
`plh_progress_wheel` component with the following `parameter_list`:
- `title`: The title attached at the bottom of the progress wheel.
- `task_total`: Total of tasks being tracked
- `task_progress`: Number of tasks marked as completed

## Git Issues

Closes #2538

## Screenshots

| Design    | Kuwait Style |
|---------------|----------------|
| <img width="260" src="https://github.com/user-attachments/assets/d7d25594-f30e-4ad0-b64e-5e60d3f7dce2">    | <img width="250" src="https://github.com/user-attachments/assets/7857a5c6-b3dc-444e-8497-6fbfd74d602d">  |

2024-11-26 14:49 UTC, esmeetewinkel reviewed
Looking great! I was wondering if it would make sense to add the gradient design that's in the Mexico app in this PR too, or that that will be a follow-up PR (I don't mind either way). 

![image](https://github.com/user-attachments/assets/5da2d00e-6f9e-49a2-a889-37ecc1e8a254)

2024-11-27 11:50 UTC, jfmcquade requested changes
This looks really nice, and the logic is nice and straightforward.

Currently, you've exposed the `task_total` and `task_progress` parameters to set the completion percentage of the component. This would mean that an author would have to add their own logic for evaluating which tasks have been completed and pass that to the component. Instead, the component should be able to take two parameters and calculate the completion percentage itself: 
1. `data_list` – the name of a data list containing rows that relate to tasks that can be completed
2. `completed_column` – the name of the column within that data list that stores the completed status of the task row

From these values, the component can then look up the data list with that name, look at the completed column and compare the total number of tasks to the number that have been completed to calculate the total progress itself.

For this reason, I think it would make sense for this component to be a variant of the existing `task-progress-bar` component, which already contains this logic. The `task-progress-bar` component does contain some other logic to support a legacy system for handling tasks, but that can be ignored. 

In order to implement this wheel as a variant of the `task-progress-bar` component, you'll need to do the following:
- Configure the `task-progress-bar` component to have variants, e.g. `bar` and `wheel`, where `bar` is default.
  - `src/app/shared/components/template/components/audio/audio.component.ts` could be a good example of how to implement variants with a default
  - Likewise, the `audio.component.html` template can be used as an example – you'll want to wrap most of the existing template code of `task-progress-bar.component.html` in an `@if(params.variant.includes("bar"))` block, and add your code from `progress-wheel.component.html` in another `@if()` block underneath.
- Move most of your component logic into `task-progress-bar.component.ts` and refactor to use the existing properties
  - i.e. `subtasksCompleted` and `subtasksTotal` can be used to calculate the completion percentage in your `getStrokeOffset()` method

2024-11-28 09:41 UTC, FaithDaka commented
Thanks @jfmcquade 
The changes have been made and PR description updated.

2024-11-28 15:41 UTC, jfmcquade requested changes
Thanks for refactoring, I think the logic fits in pretty well to the task progress bar component. I really like the animation when updating the progress on the debug template.

I have a couple of further comments (plus some minor suggestions inline):
1. I think that the component styles should be moved to `src/app/shared/components/template/components/task-progress-bar/task-progress-bar.component.scss`, out of the theme-level overrides (this will also allow you to merge master in without merge conflicts). It's a grey area, but I think it makes sense to expose that variant to other deployments, even though the styling is quite theme-specific for now.
2. On initial load, the component shows briefly with "10000%" completion and the animation glitches. I think you'll need to add a timeout to only display the progress once it has been calculated. See demo:

https://github.com/user-attachments/assets/b8facd63-3bee-4183-aa60-e6136b7b1cda

2024-11-28 15:41 UTC, jfmcquade commented on src/app/shared/components/template/components/task-progress-bar/task-progress-bar.component.ts
> +  radius = 16; // Radius of the circle
Could be good to add a comment above these three properties to indicate that they relate to the "wheel" variant

2024-11-28 15:41 UTC, jfmcquade commented on src/app/shared/components/template/components/task-progress-bar/task-progress-bar.component.ts
> +  getStrokeOffset(): number {
Again, would be good to have a comment here (JSDoc style) to indicate that this method relates to the "wheel" variant. It should also be explicitly tagged as `public`.

2024-11-29 11:29 UTC, FaithDaka commented
> Thanks for refactoring, I think the logic fits in pretty well to the task progress bar component. I really like the animation when updating the progress on the debug template.
> 
> I have a couple of further comments (plus some minor suggestions inline):
> 
> 1. I think that the component styles should be moved to `src/app/shared/components/template/components/task-progress-bar/task-progress-bar.component.scss`, out of the theme-level overrides (this will also allow you to merge master in without merge conflicts). It's a grey area, but I think it makes sense to expose that variant to other deployments, even though the styling is quite theme-specific for now.
> 2. On initial load, the component shows briefly with "10000%" completion and the animation glitches. I think you'll need to add a timeout to only display the progress once it has been calculated. See demo:
> 
>  progress.wheel.glitch.mov

@jfmcquade 
I've transferred the wheel styling to the component `scss` file and it will use an `ion-secondary` colour so that the colour changes per theme, otherwise everything else is specific to the Kuwait theme.

For the glitching, I've added the `getStrokeOffset` method to the `ngOnInit` and made 0 the default value while the percentage gets calculated. Let me know if the way it works now makes sense. The `timeout` function wasn't effective on my end.

2024-12-02 10:58 UTC, jfmcquade approved these changes
Thanks, @FaithDaka 

I've added https://github.com/IDEMSInternational/open-app-builder/pull/2558/commits/02d27798a90903173af4e5c8af81bb69ec7631bd with couple of minor changes:
- Now the progress wheel fills up from empty on initial load (previously the wheel would start full and then animate to its partially completed state, which looked odd to me)
- Minor code tidying

I think I'll be happy to merge this PR if @esmeetewinkel agrees that things are looking good

2024-12-02 13:58 UTC, esmeetewinkel commented
@FaithDaka Could the PR description be updated to reflect the latest? 

Currently the linked sheet doesn't demonstrate the task based functionality.

2024-12-03 11:54 UTC, jfmcquade commented
@FaithDaka I've updated the PR description to reflect the latest updates.

@esmeetewinkel this PR should be ready for functional testing

2024-12-03 15:22 UTC, esmeetewinkel approved these changes
Functional test passed. The animation for adding progress looks great! 

I removed the spreadsheet [component_plh_progress_wheel](https://docs.google.com/spreadsheets/d/1aXtJi0oCxsHISq6m-xwJi_R_BSpUj4wHQlO_g4LUjSY/edit?gid=2015154474#gid=2015154474) which I believe is now redundant

2024-12-03 15:22 UTC, merged