Kuwait Theme: Activity Check-in component
IDEMSInternational/open-app-builder pull request #2562
Opened 2024-11-26 18:09 UTC by FaithDaka

PR Checklist

- [x] PR title descriptive (can be used in release notes)

## Description

`plh_activity_check_in` created and styled. Corresponding debug sheet: [Link](https://docs.google.com/spreadsheets/d/1anFgMo2Uad0A9lgtKvbdjA4GyrkMvuWO90rdzMNc-SQ/edit?usp=sharing)

## Author Notes
`plh_activity_check_in` component with the following `parameter_list`:
- `id`: Activity identifier.
- `title`: The title of the component attached to the bottom
- `locked_icon_asset`: Icon that appears next to the title while the component is locked
- `locked_image_asset`: Illustration that appears while component is locked
- `unlocked_icon_asset`: Icon that appears next to the title while the component is unlocked
- `unlocked_image_asset`: Illustration that appears while component is unlocked
## Git Issues

Closes #2539 

## Screenshots
| Design    | Locked Component |  Unlocked Component |
|---------------|--------|-------------|
| <img width="250" src="https://github.com/user-attachments/assets/b10d34f3-4476-434d-b6c0-70ca3b665125">  | <img width="250" src="https://github.com/user-attachments/assets/d58a5796-a381-41f9-b371-99f877004a97">   | <img width="250" src="https://github.com/user-attachments/assets/d1b38bb0-0794-40a9-89e6-87c84fb8f935">  |

2024-11-27 15:03 UTC, jfmcquade requested changes
Nice to have this scaffolded out. I assume you're seeing the logic for handling the countdown and unlock as a placeholder that should be replaced by logic that connects to our real system of handling this data? @esmeetewinkel is that something that has been discussed/thought through already, or shall we add it to our meeting agenda?

I would also say that it probably makes sense to style the component to be centred within its div. Laying out the element so that it sits to the side of another element is something that should be handled at the authoring level (i.e. by putting the elements inside a `display_group` component).

2024-11-27 15:05 UTC, esmeetewinkel reviewed
I'm not sure how you're proposing to author the "days left". One way that would be intuitive to me is that the component can have a parameter (maybe `unlock_at`) which is a timestamp of the moment of unlocking. If this parameter value is
- falsy (undefined or empty string): don't show the "days left" progress bar + text. Button is disabled.
   ![image](https://github.com/user-attachments/assets/ab9c875f-f179-430b-9a10-cbba663ae3e6)
- a time stamp in the future: compute how many days left and display progress bar + text. Button is disabled.
   ![image](https://github.com/user-attachments/assets/83c7310b-4ec9-4725-a0fe-e15a9c26a041)
- a time stamp in the past:  don't show the "days left" progress bar + text. Button is enabled.
   ![image](https://github.com/user-attachments/assets/cfc8136a-7121-4616-8463-537766d4dcd3)

2024-11-27 15:16 UTC, esmeetewinkel commented on packages/components/plh/plh-kids-kw/components/activity-check-in/activity-check-in.component.ts
> +  private checkInTimer() {
Yes let's discuss in our next meeting. My initial thoughts are in my [comment](https://github.com/IDEMSInternational/open-app-builder/pull/2562#pullrequestreview-2465293566) below

2024-12-03 12:53 UTC, jfmcquade commented
@FaithDaka: @esmeetewinkel and I discussed how we're going to handle the countdown settings, and our plan requires the following:

I've authored a new row in the [component demo template](https://docs.google.com/spreadsheets/d/1anFgMo2Uad0A9lgtKvbdjA4GyrkMvuWO90rdzMNc-SQ/edit?gid=569531329#gid=569531329) to represent how the authoring should work, just as an example until the logic to handle the parameters is fleshed out:
<img width="600" alt="Screenshot 2024-12-03 at 12 09 38" src="https://github.com/user-attachments/assets/c32629ac-5004-401f-956f-2cf837ffce14">

The proposed changes are:
- Add two new params to this component
  - `start_date`
    - A timestamp as a string or date object
  - `countdown_text_list`
    - A list of text strings to display for each day of the countdown. E.g. `"in 1 day", "in 2 days", "in 3 days",...` etc.
    - Whilst obviously it would be more convenient to construct these strings dynamically, in order to have them properly translated we need to supply them manually
    
Then the `plh_activity_check_in` will need to handle the following logic:
- Add the `days_to_count_down` to the `start_date` value to calculate the unlock date. We want to ignore the time and just calculate the days, so that the unlock will happen at midnight on the target day.
  - use the [date-fns](https://github.com/date-fns/date-fns) library to accomplish this, it is already installed on the repo
- On init, the component should calculate the days until the unlock date and use this calculation to display in the expected way.

2024-12-12 17:00 UTC, jfmcquade commented
@FaithDaka I've added logic to handle the countdown and `locked` status, alongside various other bits of code tidying, you can see my changes in [these commits](https://github.com/IDEMSInternational/open-app-builder/pull/2562/files/d8d5b7de54e653edc7ac40fef2f9d53a667d756f..a4533c1e6a48fd59c30f6f4629e764ace4eef3d1).

I'll update the PR description to explain the new functionality

2024-12-12 17:24 UTC, jfmcquade approved these changes

2024-12-21 15:30 UTC, esmeetewinkel requested changes
I finally finished reviewing this, sorry for the delay.

1. Could the default for the component be the "locked" display (but without the countdown bar) when the `countdown_start_date` is falsy? Currently this is shows the "unlocked" display - which doesn't fit the use case. 
   ![image](https://github.com/user-attachments/assets/f3d59299-442e-4aee-a028-58d5f6f45a92)

2. I still can't manage to display the progress wheel and this component nicely side-by-side in a display group (I attempted adding `justify-content: space-between; align-items: baseline` in the `style_list` but it's still not great). What would you propose? See `module_landing` template [sheet](https://docs.google.com/spreadsheets/d/1nvyc-d_noz-W7guO6x_33c6cCXMXpexGt5HYf5T5J50/edit?gid=452625780#gid=452625780)

2024-12-23 17:54 UTC, jfmcquade commented
> 1. Could the default for the component be the "locked" display (but without the countdown bar) when the `countdown_start_date` is falsy? Currently this is shows the "unlocked" display - which doesn't fit the use case.

I've updated to reflect this in https://github.com/IDEMSInternational/open-app-builder/pull/2562/commits/ec7bd1a8dc0c52dfa45067e39333a93f1e925f4e, including a button in the [template](https://docs.google.com/spreadsheets/d/1anFgMo2Uad0A9lgtKvbdjA4GyrkMvuWO90rdzMNc-SQ/edit?gid=569531329#gid=569531329) to "unset" the `countdown_start_date` property (set to `undefined`) to test this state of the component.

<img width="240" alt="Screenshot 2024-12-23 at 17 51 02" src="https://github.com/user-attachments/assets/1d368b86-8179-4625-ad37-f325217d5c22" />

> 2. I still can't manage to display the progress wheel and this component nicely side-by-side in a display group (I attempted adding `justify-content: space-between; align-items: baseline` in the `style_list` but it's still not great). What would you propose? See `module_landing` template [sheet](https://docs.google.com/spreadsheets/d/1nvyc-d_noz-W7guO6x_33c6cCXMXpexGt5HYf5T5J50/edit?gid=452625780#gid=452625780).
>    ![image](https://private-user-images.githubusercontent.com/74557272/397936817-f3d59299-442e-4aee-a028-58d5f6f45a92.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ5NzU0ODMsIm5iZiI6MTczNDk3NTE4MywicGF0aCI6Ii83NDU1NzI3Mi8zOTc5MzY4MTctZjNkNTkyOTktNDQyZS00YWVlLWEwMjgtNThkNWY2ZjQ1YTkyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIzVDE3MzMwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM4OTYzM2U4MDQxZmUzMjU5MDRiYzVmZTJjNzk4OGFiNGQ1ZDU1MGI3NTQ1MmRmZTg5MDdhNTJmYjkzMWJmYWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.mwi75X1pUD1PCpFlF2L5y-V75lf5WCohs_7koeO_N-4)   ![image](https://private-user-images.githubusercontent.com/74557272/397936947-7154b2f0-bbe1-412f-b848-2f55cf2ef666.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ5NzU0ODMsIm5iZiI6MTczNDk3NTE4MywicGF0aCI6Ii83NDU1NzI3Mi8zOTc5MzY5NDctNzE1NGIyZjAtYmJlMS00MTJmLWI4NDgtMmY1NWNmMmVmNjY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIzVDE3MzMwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZmOWE3MDBmNTdmNTkyNTI5YWNhYTQwYTJhMDY3MWEzMGQ2YjBiMDVjZGNjNTY3NjNkOWY2OWJhNGMxNTg0M2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.0Xsz3-C3BKerBx_njnIeo0-SlMLpRHmYSVTtnJE-RUQ)

@FaithDaka would you be able to take a look at this and adjust the styling?

2024-12-30 14:36 UTC, esmeetewinkel commented
I can confirm I can set the start date to undefined in the `debug` template, after which I see the desired display of the "locked" component. I also see a console error 
```
activity-check-in.component.ts:99 [ACTIVITY CHECK-IN] Invalid date for countdown_start_date: undefined
```
This can be helpful for testing, however maybe not great to clutter our GlitchTip with these errors related to _expected_ behaviour - @jfmcquade will these appear on GlitchTip?
![image](https://github.com/user-attachments/assets/65cd4e97-2683-404b-9c1b-39ce86359c80)

I can't quite make this work on the `plh_kids_kw` deployment. My guess is that this relates to the value not being the string "undefined" but actually referring to a non-existing value in a data list. A hacky workaround could be to set the values in this data list column to be "undefined" by default - @jfmcquade let me know if I should try this.
![image](https://github.com/user-attachments/assets/d92afb4d-5f81-4bf8-81be-824db4f785f6)
![image](https://github.com/user-attachments/assets/0ade16ec-a4df-4102-8bf7-b3d8dbc207db)

2025-01-02 15:30 UTC, esmeetewinkel approved these changes
Thanks @jfmcquade, looking lots better and I can confirm the error has disappeared + item locks correctly when timestamp doesn't exist.

The only display that doesn't look great yet is the one where the countdown bar is displayed. Would it make sense to tweak that to the current image dimensions or better to leave as-is?

![image](https://github.com/user-attachments/assets/2e190f81-f274-4b0b-82dd-ad6b3a8eb10e)

2025-01-03 10:23 UTC, merged