Kuwait Theme: Add Background Image to Display Group
IDEMSInternational/open-app-builder pull request #2589
Opened 2024-12-03 13:01 UTC by FaithDaka

PR Checklist

- [x] PR title descriptive (can be used in release notes)

## Description
Adds a `background_image_asset` to `feature_display_group` component. [Link](https://docs.google.com/spreadsheets/d/1ARbNRGDer5vj9qSpRMZFrMkYifGkH3TLtDVp72YbaqU/edit?usp=sharing)
Also includes display group styling according to the Kuwait theme.

## Author Notes
New parameter list:
- `background_image_asset`: Adds a background image to the display group.
- `background_image_position`: Positions the background image (top, center, bottom). Default `top`

## Git Issues

Closes #2579

## Screenshots
| Design        |  Kuwait Style       |
|----------|-------------|
| <img width="300" src="https://github.com/user-attachments/assets/cd8f18b2-58b3-41da-ab07-b281a0c1d7c3"> | <img width="280" src="https://github.com/user-attachments/assets/e24c9c7d-963c-43f3-ae62-e246d1cb1d9f"> |
| <img width="300" src="https://github.com/user-attachments/assets/4aed572d-924f-4419-bf97-9029078b8160"> | <img width="280" src="https://github.com/user-attachments/assets/3f7d2ecb-0131-4111-ae3c-cd71022376b2"> |
| <img width="250" src="https://github.com/user-attachments/assets/a2dfd192-0178-4e90-a0e2-1d3c0639c2ab"> | <img width="250" src="https://github.com/user-attachments/assets/6930aafd-faf8-4857-a8eb-d0e826c41c05"> |

2024-12-03 13:07 UTC, FaithDaka commented
@jfmcquade I tested the concept of adding a `margin` to the text using the `style_list` column but given that it requires one to set two values (for top-bottom and left-right) then we don't get the desired effect. 
It will be helpful to discuss the need for a `spacer` component such that space can always be added between components.

2024-12-03 14:37 UTC, jfmcquade commented
> @jfmcquade I tested the concept of adding a `margin` to the text using the `style_list` column but given that it requires one to set two values (for top-bottom and left-right) then we don't get the desired effect. It will be helpful to discuss the need for a `spacer` component such that space can always be added between components.

Thanks for looking into it. Does it not work with `margin-top`? In theory we should be able to pass any valid CSS to the `style_list` column so I would have thought that setting `margin-top: 48px`, for example, could work

2024-12-03 17:09 UTC, FaithDaka commented
Oh, I was using this format: `margin: 50px 0px 0px 0px`. Using `margin-top` works fine @jfmcquade

2024-12-05 15:42 UTC, jfmcquade requested changes
I think the background image options look good.

The changes to the `box_primary` etc. variants should be pulled into a separate PR I think. I'm not sure whether we want to overwrite the `box_*` variants for the KW theme or offer new variants. Presumably we're not planning on using the default `box_*` stylings and so overwriting them may make sense, perhaps @esmeetewinkel can confirm.

Would be good to have those changes broken out into a separate PR for that reason, but if we're sure we're happy to override then they can stay with this PR, but the title and description should be updated.

2024-12-06 18:32 UTC, jfmcquade commented
Hi @FaithDaka, I have broken out the display group styling for the `box_*` variants to another PR, see #2604.

I've also added some additional changes with https://github.com/IDEMSInternational/open-app-builder/pull/2589/commits/f7c6ecfef6e5c2c4c3be2b0e34157a8b085443cc to enable the styling of your designs to be achievable. I will update the PR description with what I've added.

2024-12-06 18:41 UTC, jfmcquade approved these changes

2024-12-09 18:43 UTC, chrismclarke requested changes
Definitely a nice feature to have and good way to address the design need for wavy backgrounds (assume can just use an SVG background image now)

See on minor (blocking) issue inline, I'll take a quick look to see if I can propose changes to fix.

Appreciate the example sheets as well, @jfmcquade - it would be good to merge with other display_group examples into the `feature_display_group` sheet

2024-12-09 18:43 UTC, chrismclarke commented on src/app/shared/components/template/components/layout/display-group/display-group.component.html
> +    "
nit(blocking): assigning styles in this way looks quite messy. Given the sticky host still renders the child templated content then the child content should be the place to handle this. I'm not sure if maybe I've missed a use case here?

2024-12-09 19:08 UTC, chrismclarke commented
I've tested removing all references to `stickyBackground` and `--sticky-background` and I can't see any difference on my side, so guessing it might be an issue related to theming. @jfmcquade or @FaithDaka would one of you be able to check  

I also noticed a minor issue where the background image would be applied to all display groups even if not specified (with a URL to an undefined image). I've updated with the above changes as part of #2612)

2024-12-10 12:43 UTC, jfmcquade commented
> I also noticed a minor issue where the background image would be applied to all display groups even if not specified (with a URL to an undefined image). I've updated with the above changes as part of #2612)

Thanks, makes sense

> I've tested removing all references to `stickyBackground` and `--sticky-background` and I can't see any difference on my side, so guessing it might be an issue related to theming. @jfmcquade or @FaithDaka would one of you be able to check

I've added a comment to #2612 as to why something along those lines is needed, and have pushed an alternative implementation, let me know what you think.

@FaithDaka I've noticed an additional issue: on wider screen sizes, the limits of the image are clearly visible. Whilst we don't make an effort to support desktop screen dimensions, we should at least be supporting tablets and larger phones. I can't think of a simple way to resolve this, can you?
<img width="480" alt="Screenshot 2024-12-10 at 12 41 54" src="https://github.com/user-attachments/assets/c79235de-e37c-4a17-9130-4caa49bae3f7">

2024-12-10 19:34 UTC, chrismclarke commented
> @FaithDaka I've noticed an additional issue: on wider screen sizes, the limits of the image are clearly visible. Whilst we don't make an effort to support desktop screen dimensions, we should at least be supporting tablets and larger phones. I can't think of a simple way to resolve this, can you? 

I think there's a couple levels of issue, some easier to fix than others.
For the immediate alignment issue, it will be partially solved using the `backround_image_position` author variable exposed as the header can be fixed `right top;` which I think looks better

![image](https://github.com/user-attachments/assets/12163b5b-165c-4d5b-8ae3-330a00fe7fa2)

But then you have the issue of whether the sticky group should max the max content width that the main templated content does or not (as currently all sticky content 100% width). 

![image](https://github.com/user-attachments/assets/b33f4b18-6db5-4346-8ea9-f721950676b1)

I think the most sensible default behaviour would be to keep the sticky header as full width (so background image can be relative to entire page), but all child components set with the same `max-width: var(--content-max-width);` otherwise assigned at the template-container level. End result would look like

![image](https://github.com/user-attachments/assets/42c61985-2e76-4b7c-93f9-ae0dd89791cc)

I'm not sure if it would be best to include that as part of this pr or a separate one

2024-12-11 05:01 UTC, FaithDaka commented
@jfmcquade 
From @chrismclarke suggestion it makes sense to change the html layout such that the outer `div` with the `background-asset` spreads 100% while the inner content maintains a `max-width`. But also the outer `div` would need a `max-width` otherwise if the web-view is projected using a large TV then the background image would still spread to fill the screen and fail to maintain its appearance.

2024-12-12 20:46 UTC, chrismclarke approved these changes
Changes from #2612 now included which I think address the only issues I had, @FaithDaka you might be interested to note the changes particularly how to assign a solid background colour when using a combination of text and image backgrounds. 

A couple specific sticky header/footers with background images have also now been included in the general [feature_display_group](https://docs.google.com/spreadsheets/d/1ARbNRGDer5vj9qSpRMZFrMkYifGkH3TLtDVp72YbaqU/edit?gid=1231713195#gid=1231713195) sheet 

(sidenote - really all the sheets in this google sheet document should be split into standalone component sheets)

@jfmcquade - I've retagged you for final review just so that you can sign-off on the changes merged from #2612

2024-12-18 11:33 UTC, esmeetewinkel requested changes
I'm struggling a little to understand from the PR description how the different parameters (are intended to) work. 

**Clarifications:**
1. I'm understanding that `background_image_position` can be one of top / center / bottom (vertical position), _but can also contain left / right (horizontal position)_. Default is top + horizontally centred. If this is correct can this be added tot he PR description?

2. The description of `style: background_solid` in the PR notes is cut off. This seems to be the default - I don't observe any difference when I do / don't include this parameter. I don't understand how to achieve a transparent background, as in the design:
![image](https://github.com/user-attachments/assets/da8560ea-9051-42d9-bdc3-b0c85763a26c)

**Bugs:**
1. When the `background_image_position` is set to `top right` the image doesn't remain glued to the top on narrow screens. 
   
   https://github.com/user-attachments/assets/98fb1fb2-20fd-41e4-9987-e0e9c58a88aa

2. The `background_image_position` left / right should flip in RTL and the background image should be flipped. 
   Current view in RTL:
   ![image](https://github.com/user-attachments/assets/d27ec3c8-a20e-4ce4-8bfb-4e1fca2dc0ff)

2025-01-03 10:55 UTC, jfmcquade commented
> **Clarifications:**
> 
> 1. I'm understanding that `background_image_position` can be one of top / center / bottom (vertical position), _but can also contain left / right (horizontal position)_. Default is top + horizontally centred. If this is correct can this be added tot he PR description?

Good point, I've clarified in the PR description:
- `background_image_position`: Positions the background image. Default `top center`
  - The possible values for this parameter are those of the CSS `background-position` property, see "Property Values" table [here](https://www.w3schools.com/cssref/pr_background-position.php). This means that, for example, the x and y positioning of the  background image can be set via, e.g., `background_image_position: right bottom`

> 2. The description of `style: background_solid` in the PR notes is cut off. This seems to be the default - I don't observe any difference when I do / don't include this parameter. I don't understand how to achieve a transparent background, as in the design:

Well spotted. I think in various discussions and sources of changes something got lost, and the default solid background colour wasn't removed properly. I've rectified this and you can see the difference between the sticky top display group with `style: background_solid` and the sticky bottom display group with the default background colour as transparent:

<img width="240" alt="Screenshot 2025-01-03 at 10 52 51" src="https://github.com/user-attachments/assets/0118c781-484c-4eb2-8c5a-8dbb7359af7b" />

Note that this does mean the default is changing for the sticky display group. If there are other places in the app that use a sticky display group, they may need to have `style: background_solid` set on them in order to preserve the behaviour of having a solid background.

2025-01-03 11:27 UTC, jfmcquade commented
> **Bugs:**
> 
> 1. When the `background_image_position` is set to `top right` the image doesn't remain glued to the top on narrow screens.

The display group at the top of the [debug template](https://docs.google.com/spreadsheets/d/1ARbNRGDer5vj9qSpRMZFrMkYifGkH3TLtDVp72YbaqU/edit?gid=1231713195#gid=1231713195) previously just had `background_image_position: right`. Updating this to `background_image_position: right top` resolves the issue:

<img width="100" alt="Screenshot 2025-01-03 at 10 59 18" src="https://github.com/user-attachments/assets/f2a02be8-511a-494f-bd72-21b277167d63" />

> 2. The `background_image_position` left / right should flip in RTL and the background image should be flipped.

This is proving quite difficult to implement, because of the way the CSS background images work. I think it would make sense for me to merge this PR as-is if possible, then I'll work on this as a follow-up.

> 3. On some screen ratios (e.g. Moto G4 and Samsung Galaxy S8+) I'm seeing a faint blue line underneath the image

I believe this is an issue due to the fact that source image is not a true svg, but rather a png image embedded in an svg. @FaithDaka, can you supply the image file as a true vector svg? Or if that isn't available, could you provide the asset as a png? This doesn't block this pR being merged, but would be good to have for the production deployment.

2025-01-03 11:33 UTC, esmeetewinkel commented
> I believe this is an issue due to the fact that source image is not a true svg, but rather a png image embedded in an svg. @FaithDaka, can you supply the image file as a true vector svg? Or if that isn't available, could you provide the asset as a png? This doesn't block this pR being merged, but would be good to have for the production deployment.

No need for @FaithDaka to provide these images, as they have been changed and I'm getting the new versions from the illustrator directly.

2025-01-03 13:49 UTC, esmeetewinkel approved these changes

2025-01-03 13:50 UTC, merged