Kuwait Theme: Settings page styling
IDEMSInternational/open-app-builder pull request #2598
Opened 2024-12-04 15:10 UTC by FaithDaka

PR Checklist

- [x] PR title descriptive (can be used in release notes)

## Description
Includes styling for components on the Settings page. [Button](https://docs.google.com/spreadsheets/d/1OmgZICjM5EMT1KgLOU_ovDljRF_SPlpQAgkKWPrNX0s/edit?usp=sharing), [Text](https://docs.google.com/spreadsheets/d/1iZHeAAZAQ8q-XNKrW_ww3yvPUVGwc407uhAF7vu1TtM/edit?usp=sharing)

## Author Notes
Use the button params: `style: no-background` to achieve the button look for the options list
| Design | Component |
| ----------- | ----------- |
| <img width="250" src="https://github.com/user-attachments/assets/a79a2c05-f6a4-40e1-b545-c795d42cf179"> | <img width="250" src="https://github.com/user-attachments/assets/c5a2435a-8814-4598-ab28-3d2e18101216"> |

Use the text params: `style: list-title` to achieve the text look for the options title
| Design | Component |
| ----------- | ----------- |
| <img width="250" src="https://github.com/user-attachments/assets/a79a2c05-f6a4-40e1-b545-c795d42cf179"> | <img width="250" src="https://github.com/user-attachments/assets/8d268a2f-76d6-445c-afac-dee63a3203bb"> |

Use the text params: `style: page-title` to achieve the text look for the settings page title
| Design | Component |
| ----------- | ----------- |
| <img width="250" src="https://github.com/user-attachments/assets/c592786a-8ead-4670-ab0d-bb9fd67adcf5"> | <img width="250" src="https://github.com/user-attachments/assets/ed1aa33c-bc0c-4433-bf41-43e56ebdeebe"> |

## Git Issues

Closes #2582

2024-12-09 15:57 UTC, jfmcquade requested changes
We're trying to move away from setting styles via the `style` parameter – instead, named styles like `list-title` and `page-title` should be `variant`s. This makes it easier to track what variant(/style) options are available for a given component, and also allows `style` to be used for applying global styles that make sense on multiple components (we haven't implemented this yet, but the plan is outlined in #1971 if you're interested 😅).

I would also suggest that `page-title` and `list-title` be variants of the dedicated `title` component (`src/app/shared/components/template/components/title/title.component.ts`), unless there is good reason to use the `text` component.

2024-12-12 10:02 UTC, FaithDaka commented
Changes made @jfmcquade 
Though I failed to understand how to use the title template for review. The title output is `undefined`
<img width="210" src="https://github.com/user-attachments/assets/7100e14f-aeba-416b-b294-8c02c5e9c1cc"> <img width="210" src="https://github.com/user-attachments/assets/d797e33b-8ba7-454d-9962-9b97dcba625c">

2024-12-17 14:34 UTC, jfmcquade requested changes
@fait
For the button component, there are some issues with achieving your design by using the round button component inside a child row of the button component:
- The spacing doesn't look quite right
- The round button component is a different click target to its parent button

I think it would be better to pass in the secondary icon as an additional parameter to the `button` component, e.g. an `icon_secondary` param, and then pass this icon to the `end` slot of the `ion-button` inside `src/app/shared/components/template/components/button/button.component.html`, something like this:

<img width="600" alt="Screenshot 2024-12-17 at 14 32 36" src="https://github.com/user-attachments/assets/a771af25-48bc-4e09-a406-427e2fb49a4a" />

> Changes made @jfmcquade Though I failed to understand how to use the title template for review. 

You're right, it looks like the [comp_title](https://docs.google.com/spreadsheets/d/1pBCI7KkNNtF9sQAs_l_hcdjjFfdjC4vEL4jvF5sNk9c/edit?gid=569531329#gid=569531329) template wasn't fit for purpose. I've updated it now. You can add rows to demo the new variants included in this PR when you have finalised the names

2024-12-17 14:37 UTC, jfmcquade commented on src/app/shared/components/template/components/button/button.component.ts
> +  iconPosition: "left" | "right";
This param can be removed as I don't believe it's used

2024-12-22 11:55 UTC, FaithDaka commented
Changes made @jfmcquade

2024-12-30 13:12 UTC, esmeetewinkel requested changes
Thanks, looking good. 

**Titles**
I found that the alignment of the two title variants is incorrect when the title text wraps on multiple lines for RTL. @jfmcquade am I correct to assume that's also addressed by PR #2658?

**Transparent button with two icons**
I can see the icons swap when a RTL language is selected (correctly). I guess also the button text needs to become right-aligned?

Currently on LTR vs RTL: 
![image](https://github.com/user-attachments/assets/e9dc95ef-4d2f-49aa-b85d-fa8eaedc3ed3)
![image](https://github.com/user-attachments/assets/edc116c2-e628-446b-9431-6661992e8acd)

2024-12-31 07:59 UTC, FaithDaka commented
Support added for RTL @esmeetewinkel 

<img width="320" src="https://github.com/user-attachments/assets/3ecbb03d-18b1-4107-a8fb-956cc3b784d4">

2024-12-31 13:34 UTC, esmeetewinkel reviewed
Thanks @FaithDaka for updating the text alignment.

I still can't see the leaf-icon being reflected (like it does in your screenshot) - am I missing something?

Screenshots LTR vs RTL:
![image](https://github.com/user-attachments/assets/97f3c3a4-1d18-4a3d-b7d6-d98b374ae463)   ![image](https://github.com/user-attachments/assets/1a168d4a-a52a-47a0-a90f-61ae5b503d51)

2025-01-02 15:10 UTC, jfmcquade commented
> Thanks @FaithDaka for updating the text alignment.
> 
> I still can't see the leaf-icon being reflected (like it does in your screenshot) - am I missing something?
> 
> Screenshots LTR vs RTL: ![image](https://private-user-images.githubusercontent.com/74557272/399479382-97f3c3a4-1d18-4a3d-b7d6-d98b374ae463.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU4MTg3MjUsIm5iZiI6MTczNTgxODQyNSwicGF0aCI6Ii83NDU1NzI3Mi8zOTk0NzkzODItOTdmM2MzYTQtMWQxOC00YTNkLWI3ZDYtZDk4YjM3NGFlNDYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTAyVDExNDcwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc5YTE5ZjE2ZjkyNTFmMGFjY2Y3MDEyMjUxNDRkMTVhYTgwMmRkM2ZmZWI5Nzc2NGMyYTNlNzUyNWM5Nzk0NDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.PTVIqFbgcW4gLyOkJPCzJevPoHCz-D_Qb3nkONUNNxo) ![image](https://private-user-images.githubusercontent.com/74557272/399479279-1a168d4a-a52a-47a0-a90f-61ae5b503d51.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU4MTg3MjUsIm5iZiI6MTczNTgxODQyNSwicGF0aCI6Ii83NDU1NzI3Mi8zOTk0NzkyNzktMWExNjhkNGEtYTUyYS00N2EwLWE5MGYtNjFhZTViNTAzZDUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTAyVDExNDcwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAyNGNkMjgyODI4YWVlMjFmYTk0NDZlZjMwYzA1ZWM2MzBiZWM0ZmZlOWNkZGRkZGU1NWIyNTBhN2UwOWNhNDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.cy3KKMf8DjZZ_IKDmZWfEyWWsz12JNRCNzW6ALNMGVM)

@esmeetewinkel 
I've pushed changes so that the secondary icon can be the name of an ion-icon – e.g. `chevron-forward` as it is in [comp_button](https://docs.google.com/spreadsheets/d/1OmgZICjM5EMT1KgLOU_ovDljRF_SPlpQAgkKWPrNX0s/edit?gid=569531329#gid=569531329). Ionic handles flipping these "forward" and "background" icons appropriately in accordance with the language direction, so the demo in the component template behaves as expected:
<img width="200" alt="Screenshot 2025-01-02 at 15 06 59" src="https://github.com/user-attachments/assets/819745fc-265f-4741-88cf-6991f10a2609" />
<img width="200" alt="Screenshot 2025-01-02 at 15 07 09" src="https://github.com/user-attachments/assets/2f4595be-5cfd-43e8-8476-e5b231b841e6" />

2025-01-02 15:53 UTC, esmeetewinkel approved these changes
Functional test passed

2025-01-03 16:26 UTC, merged