Kuwait Theme: Custom styling for display-group 'box_*' variants
IDEMSInternational/open-app-builder pull request #2604
Opened 2024-12-06 17:26 UTC by jfmcquade

PR Checklist

- [x PR title descriptive (can be used in release notes)

## Description

Breaks out changes originally included in #2589.

Adds

## Git Issues

Closes #

## Screenshots/Videos

| Design        |  Kuwait Style       |
|----------|-------------|
| <img width="250" src="https://github.com/user-attachments/assets/a2dfd192-0178-4e90-a0e2-1d3c0639c2ab"> | <img width="250" src="https://github.com/user-attachments/assets/6930aafd-faf8-4857-a8eb-d0e826c41c05"> |

2024-12-16 12:39 UTC, esmeetewinkel requested changes
Looking nice! LTR is working well, but the component doesn't currently adapt to RTL. Could that be added here? 

![image](https://github.com/user-attachments/assets/f5d99e36-9b61-44b2-abce-7ae6574fc7b9)

2024-12-18 13:59 UTC, esmeetewinkel commented
> Looking nice! LTR is working well, but the component doesn't currently adapt to RTL. Could that be added here?

@FaithDaka is this something you could look at?

2025-01-02 15:33 UTC, jfmcquade commented
@esmeetewinkel I've pushed changes so that the styling will adjust for RTL languages:

<img width="200" alt="Screenshot 2025-01-02 at 15 30 04" src="https://github.com/user-attachments/assets/9bc3318e-410f-4422-b49a-261dbe890c28" />
<img width="200" alt="Screenshot 2025-01-02 at 15 30 15" src="https://github.com/user-attachments/assets/4557dd66-2b90-4e76-b03a-7c430791181a" />

I believe it should be good to merge if it looks right to you.

@FaithDaka tagging you for awareness, the CSS properties I've used in https://github.com/IDEMSInternational/open-app-builder/pull/2604/commits/3c77723ee84bafb8272878851b88fb0ae65724c1 were new to me

2025-01-02 15:49 UTC, esmeetewinkel approved these changes
Functional test passed

2025-01-02 15:49 UTC, merged