fix: pop-up close button position for RTL languages
IDEMSInternational/open-app-builder pull request #2660
Opened 2024-12-30 12:36 UTC by jfmcquade

PR Checklist

- [x] PR title descriptive (can be used in release notes)

## Description

Handles repositioning the pop-up close button when the app language direction is RTL. Changes applied to both fullscreen and non-fullscreen pop-ups.

## Git Issues

Closes #2618

## Screenshots/Videos

Pop-ups launched from [example_pop_ups](https://docs.google.com/spreadsheets/d/1K9JZ9Glnj73CFJmpfGIRa5dRA2TBxSsJmaguV6GL8Pc/edit?gid=402992224#gid=402992224):

<img width="200" alt="Screenshot 2024-12-30 at 12 35 08" src="https://github.com/user-attachments/assets/93d8534c-c4b2-482b-939a-6ca7444f1603" />

<img width="200" alt="Screenshot 2024-12-30 at 12 35 39" src="https://github.com/user-attachments/assets/8f3ae3f8-5479-469e-83dc-03efff821b2a" />

<img width="200" alt="Screenshot 2024-12-30 at 12 35 55" src="https://github.com/user-attachments/assets/1c6ee330-0fa1-4c61-8e5b-d0a98dcf40d4" />

2024-12-30 12:57 UTC, esmeetewinkel approved these changes
Functional test passed on PR preview link

2024-12-31 07:52 UTC, chrismclarke requested changes
Nice to have things displaying correctly, although I think it would be good if possible to find a solution that doesn't require detecting ltr/rtl so much at the component level. 

I first attempted passing down a CSS custom property from the app component that defined an `--is-rtl` property and conditionally style using the new(ish) container style queries syntax to apply CSS conditionally based on the inherited property:
https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_containment/Container_size_and_style_queries

This did work, although I then realised it's probably better to just use insets in a similar way to what you did on #2661 as insets should automatically change with text direction

So I've opened https://github.com/IDEMSInternational/open-app-builder/pull/2664 targeting this branch. Let me know what you think @jfmcquade

2024-12-31 10:37 UTC, jfmcquade commented
Thanks @chrismclarke, I've merged your suggestions with the caveat that the pop-up component does need to set its own `dir` attribute, as it is sometimes rendered outside of the main app component, see #2645.

> I first attempted passing down a CSS custom property from the app component that defined an `--is-rtl` property and conditionally style using the new(ish) container style queries syntax to apply CSS conditionally based on the inherited property: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_containment/Container_size_and_style_queries

This is a good pattern that I may implement going forwards if it's appropriate for outstanding RTL issues.

2024-12-31 17:00 UTC, chrismclarke approved these changes

2024-12-31 17:02 UTC, merged